export PATH="$HOME/.local/clojure/bin:$PATH"
export PATH="$HOME/.local/chicken/bin:$PATH"
export PATH="$HOME/.local/racket/bin:$PATH"
export PATH="$HOME/.local/idris2/bin:$PATH"
export PATH="$HOME/.local/elixir/bin:$PATH"
export PATH="$HOME/.local/maven/bin:$PATH"
export PATH="$HOME/.local/cmake/bin:$PATH"
export PATH="$HOME/.local/chez/bin:$PATH"
export PATH="$HOME/.local/julia/bin:$PATH"
export PATH="$HOME/.local/python/bin:$PATH"
export PATH="$HOME/.local/jdk/bin:$PATH"
export PATH="$HOME/.local/python/bin:$PATH"
export PATH="$HOME/.local/erlang/bin:$PATH"
export PATH="$HOME/.local/dotnet:$PATH"
export PATH="$HOME/.local/opam/bin:$PATH"
export PATH="$HOME/.local/ruby/bin:$PATH"
export PATH="$HOME/.local/go/bin:$PATH"
export GOPATH="$HOME/.local/go/go"
export PATH="$HOME/.local/node/lts/20.11/bin:$PATH"
export PATH="$HOME.ghcup/bin:$PATH"
export PATH="$HOME/.cabal/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/share/coursier/bin:$PATH"
export PATH="$HOME/.pack/bin:$PATH"
export DOTNET_ROOT="$HOME/.local/share/dotnet/"
[[ ! -r $HOME/.opam/opam-init/init.zsh ]] || source $HOME/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null
[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env"
. "$HOME/.cargo/env"
