[general]
import = ["mytilus_light.toml"]
live_config_reload = true

[window]
decorations = "None"

[font]
normal = { family = "TermSans", style = "Regular" }
bold = { family = "TermSans", style = "Bold" }
italic = { family = "TermSerif", style = "Regular" }
bold_italic = { family = "TermSerif", style = "Bold" }
size = 18.0
